### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by ProjectCleverWeb** [adamdburton/destiny-2-api-client#1]
Is there any chance you could provide some sample code for using this library?

**Comment by ProjectCleverWeb** [comment]
It took some time, but I was able to discern the code well enough to get myself started. Here is what I have so far:

```
<?php

require_once __DIR__.'/vendor/autoload.php';

use GuzzleHttp\Client as GuzzleClient;

$guzzle_client = new GuzzleClient(['verify' => FALSE]);
$client = new AdamDBurton\Destiny2ApiClient\Api('REDACTED', $guzzle_client);

$result = $client->destiny2->searchDestinyPlayer(2, 'WIN__MAN')->getData();
$player = $result[0];

$player->iconPath; // PSN Icon
$player->membershipType; // Membership Type
$player->membershipId; // Account ID
$player->displayName; // Display Name

$result = (array) $client->destiny2->getProfile(2, $player->membershipId, 200)->getData()->characters->data;

$characters = $result;

$p_char = $characters['2305843009262152964'];

$result = $client->destiny2->getHistoricalStats(2, $player->membershipId, $p_char->characterId)->getData();

print_r($result);

```

**Comment by adamdburton** [comment]
I've added a [README.md](https://github.com/adamdburton/destiny-2-api-client/blob/master/README.md) file with example usage.

P.S. You don't _have_ to pass a Guzzle instance through as a second parameter, one is created inside the class.

**Comment by ProjectCleverWeb** [comment]
Thank you!

Also, due to my local environment I need to turn off SSL verification. Which is why I am making my own guzzle instance.
