### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by mikewojtkiewicz** [adamdburton/destiny-2-api-client#2]
I'm having issues with SSL verification and your code. How can I add set ssl verify to false?

**Comment by adamdburton** [comment]
You can pass in your own Guzzle client.

`$api = new AdamDBurton\Destiny2ApiClient\Api('{api-key}', new GuzzleClient([ 'verify' => false ]));`

**Comment by mikewojtkiewicz** [comment]
That actually didn't work for me either. I ended up changing your code a bit: on client.php line 42 I change it to $client = new GuzzleClient(['verify' => false]);
